import Layout from '../components/layout'
import '../styles/globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import 'bootstrap-icons/font/bootstrap-icons.css';
import Head from "next/head";
import {useEffect} from "react"
function MyApp({ Component, pageProps }) {
  useEffect(()=>{
    import("jquery/dist/jquery")
    import("bootstrap/dist/js/bootstrap");
    
},[])
  return (<>

    <Head>
        <title>Ahmet Öztürk</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Layout>
     <Component {...pageProps} />
     </Layout>
  
  </>

  )
 
  
}

export default MyApp
